### ISSUE TITLE
Freeze when plug/unplug power

### ISSUE THREAD

**Issue by FammasMaz** [ahianf/dell-vostro-3468-hackintosh#4]
I also have the same laptop and have my own opencore setup. I was facing the issue where plugging in power or changing brightness using f11/f12 freezes everything. Have to force reboot. This happened after you switched from XOSI to GPI0. I'm curious why did you switch in the first place? On this laptop we dont need GPI0 Pinning SSDT (According to Voodooi2c guide cuz our ACPI ID is lower than 0x2F). I first tried everything without XOSI or GPI0, and everything worked apart from these freezes. I added XOSI to fix those freezes as said my a comment by rehabman. Fixed everything, the only problem is that I wanted to get rid of XOSI but without that, things freeze. Same thing for your repo. Are you facing the same?

Reference to issue and solution: https://www.tonymacx86.com/threads/solved-power-plug-unplug-freeze.240185/post-1647431

**Comment by ahianf** [comment]
Freezing when connected/disconnected is a issue arising from no XOSI patching.
I did switch because as Dortania guide says, using XOSI can break Windows booting, and I prefer doing my own tailored ACPI tables. My laptop is working fine, no freezes when changing its power state.

As you say, we don't need GPI0 _pinning_, but that don't mean we don't have to use GPI0/XOSI, in fact it is neccesary to avoid halting when changing power state and to get use of trackpad functionality.

With the last commit, now my repo has patches which apply only to my hardware, so this can cause issues with another laptops except my own.

So try this. Revert to commit 8eee780bad526c0310a0fb56078e9d1a734c5854 from July 29, and if that is working for you without problem, that means you should use XOSI. So delete GPI0, replace with XOSI, and download all prebuilt ACPI files from Dortania (use the commit from July 29 as reference).

**Comment by FammasMaz** [comment]
You can close the issues, but please assist me if you can. Xosi works fine but i need to switch to GPI0 for windows too. The point that im not understanding is, that i have the same _STA method as you and literally the same SSDT-GPI0 as you. I compared all your other SSDTs as well. They are exactly the same. Do you have a clue why is the system halting for me and not for you? Did you change something in config.plist? I do have to look under _sta method in my dsdt only right?

**Comment by ahianf** [comment]
Yes, look at the _STA method.

Did you make your ssdt in Windows/Linux. If you make it in macOS, you'll get your patched DSDT from OpenCore (already patched).

That the only thing i could think of.

**Comment by FammasMaz** [comment]
Apparently it was a BIOS issue. I updated the BIOS and its fine now, however, it broke my brightness keys remap patch...have to look for a way to fix that. That patch only works with XOSI :p

**Comment by ahianf** [comment]
Thanks for the info, will add to readme
